# ========================== Jackpot CI ==========================
# Runs: Restore → Build → Unit Tests (auto-discovered) → Coverage Merge + Gate (JsonSummary) → Integration Tests → Publish Reports
# =================================================================

trigger:
  - main

variables:
  DOTNET_SDK: '8.0.x'
  BUILD_CONFIGURATION: 'Release'
  SOLUTION: 'JackpotPlot.sln'
  COVERAGE_THRESHOLD: '70'                       # Minimum total line % required (gate)
  COVERAGE_EXCLUDE_BY_FILE: '**/Migrations/*.cs;**/Generated/**/*.cs;**/bin/**;**/obj/**'
  NUGET_PACKAGES: '$(Pipeline.Workspace)/.nuget/packages'

pool:
  vmImage: 'ubuntu-latest'

steps:
  # ---------------- Checkout ----------------
  - checkout: self
    fetchDepth: 0

  # ---------------- .NET SDK ----------------
  - task: UseDotNet@2
    displayName: "Install .NET SDK $(DOTNET_SDK)"
    inputs:
      packageType: 'sdk'
      version: '$(DOTNET_SDK)'

  # ---------------- Restore & Build ----------------
  - script: |
      set -euo pipefail
      export NUGET_PACKAGES="$(NUGET_PACKAGES)"
      dotnet restore "$(SOLUTION)"
      dotnet build "$(SOLUTION)" -c "$(BUILD_CONFIGURATION)" --no-restore
    displayName: 'dotnet restore + build'

  # ---------------- Coverage Tools ----------------
  - script: |
      set -euo pipefail
      dotnet tool install --global coverlet.console
      dotnet tool install --global dotnet-reportgenerator-globaltool
      echo '##vso[task.prependpath]'"$HOME/.dotnet/tools"
    displayName: 'Install coverlet + reportgenerator'

  # ---------------- Unit Tests + Coverage + Gate (JsonSummary) ----------------
  - script: |
      set -euo pipefail

      OUT_ROOT="$(Build.SourcesDirectory)/TestResults"
      TRX_DIR="$OUT_ROOT"
      COV_DIR="$OUT_ROOT/coverage"
      HTML_DIR="$OUT_ROOT/Coverage/Report"
      SUMMARY_JSON="$HTML_DIR/Summary.json"
      mkdir -p "$TRX_DIR" "$COV_DIR" "$HTML_DIR"

      threshold=$(COVERAGE_THRESHOLD)
      echo "Coverage threshold (line,total): ${threshold}%"

      # Discover Unit test projects
      mapfile -t UNIT_TESTS < <(git ls-files '**/*Unit.Tests.csproj' | sort)
      if [ "${#UNIT_TESTS[@]}" -eq 0 ]; then
        echo "No Unit test projects found."
        exit 1
      fi

      MERGED_JSON=""

      for csproj in "${UNIT_TESTS[@]}"; do
        name="$(basename "$csproj")"            # e.g. JackpotPlot.Domain.Unit.Tests.csproj
        base="${name%.csproj}"                  # JackpotPlot.Domain.Unit.Tests
        sut_prefix="${base%.Unit.Tests}"        # JackpotPlot.Domain
        if [[ "$sut_prefix" == "$base" ]]; then sut_prefix="JackpotPlot"; fi

        include_filter="[${sut_prefix}*]*"
        test_assembly_glob="$(dirname "$csproj")/bin/$(BUILD_CONFIGURATION)/**/${base}.dll"
        out_json="$COV_DIR/${base}.json"

        echo ">>> Running: $name"
        echo "    SUT Include: $include_filter"
        echo "    Output JSON: $out_json"

        if [ -n "${MERGED_JSON}" ]; then
          coverlet $test_assembly_glob \
            --target "dotnet" \
            --targetargs "test \"$csproj\" -c $(BUILD_CONFIGURATION) --no-build --logger trx;LogFileName=${base}.trx --results-directory \"$TRX_DIR\"" \
            --include "$include_filter" \
            --exclude-by-file "$(COVERAGE_EXCLUDE_BY_FILE)" \
            --format json \
            --output "$out_json" \
            --merge-with "$MERGED_JSON"
        else
          coverlet $test_assembly_glob \
            --target "dotnet" \
            --targetargs "test \"$csproj\" -c $(BUILD_CONFIGURATION) --no-build --logger trx;LogFileName=${base}.trx --results-directory \"$TRX_DIR\"" \
            --include "$include_filter" \
            --exclude-by-file "$(COVERAGE_EXCLUDE_BY_FILE)" \
            --format json \
            --output "$out_json"
        fi

        # Always advance the merge anchor to the latest file
        MERGED_JSON="$out_json"
      done

      echo ">>> Generating HTML + Cobertura + JsonSummary"
      reportgenerator \
        -reports:"$COV_DIR/*.json" \
        -targetdir:"$HTML_DIR" \
        -reporttypes:"Cobertura;HtmlInline_AzurePipelines;JsonSummary"

      echo ">>> Gating from JsonSummary: $SUMMARY_JSON"
      if ! command -v jq >/dev/null 2>&1; then
        sudo apt-get update -y && sudo apt-get install -y jq
      fi

      # ReportGenerator JsonSummary -> summary.lineCoverage (e.g., 13.84)
      line_cov=$(jq -r '.summary.lineCoverage' "$SUMMARY_JSON")
      echo "Total line coverage: ${line_cov}%"

      # Compare as integers to avoid float quirks
      lc_int=$(printf "%.0f" "$line_cov")
      th_int=$(printf "%.0f" "$threshold")

      if [ "$lc_int" -lt "$th_int" ]; then
        echo "Coverage gate FAILED: ${line_cov}% < ${threshold}%"
        exit 2
      else
        echo "Coverage gate PASSED: ${line_cov}% ≥ ${threshold}%"
      fi
    displayName: 'Unit tests: merge coverage + gate + report'

  # ---------------- Publish Unit Test Results ----------------
  - task: PublishTestResults@2
    displayName: 'Publish Unit test results (.trx)'
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '$(Build.SourcesDirectory)/TestResults/*.trx'
      searchFolder: '$(Build.SourcesDirectory)/TestResults'
      testRunTitle: 'Unit Tests'
      mergeTestResults: true
      failTaskOnFailedTests: true

  # ---------------- Publish Code Coverage ----------------
  - task: PublishCodeCoverageResults@2
    displayName: 'Publish Unit test coverage (Cobertura)'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/TestResults/Coverage/Report/Cobertura.xml'
      reportDirectory: '$(Build.SourcesDirectory)/TestResults/Coverage/Report'
      failIfCoverageEmpty: true

  # ---------------- Integration Tests ----------------
  - script: |
      set -euo pipefail
      mapfile -t INTEGRATION_TESTS < <(git ls-files '**/*Integration.Tests.csproj' | sort)
      if [ "${#INTEGRATION_TESTS[@]}" -gt 0 ]; then
        for csproj in "${INTEGRATION_TESTS[@]}"; do
          dotnet test "$csproj" -c "$(BUILD_CONFIGURATION)" --no-build \
            --logger trx;LogFileName="$(basename "${csproj%.csproj}").trx" \
            --results-directory "$(Build.SourcesDirectory)/TestResults"
        done
      else
        echo "No Integration tests found."
      fi
    displayName: 'Integration tests (no coverage gate)'

  # ---------------- Artifacts ----------------
  - task: PublishPipelineArtifact@1
    displayName: 'Publish coverage HTML artifact'
    inputs:
      targetPath: '$(Build.SourcesDirectory)/TestResults/Coverage/Report'
      artifact: 'coverage-report'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish raw test assets (trx + json)'
    inputs:
      targetPath: '$(Build.SourcesDirectory)/TestResults'
      artifact: 'test-assets'